name: Deploy to Azure VPS

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install SSH key
      uses: webfactory/ssh-agent@v0.7.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Add known hosts
      run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

    - name: Run deployment commands
      run: |
        ssh ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} << 'EOF'
        sudo chown -R $USER:$USER /var/www/recruitment-backend
        sudo chmod -R 777 /var/www/recruitment-backend
        
        cd /var/www/recruitment-backend
        
        # Fix git ownership issue
        git config --global --add safe.directory /var/www/recruitment-backend
        
        # Pull latest changes
        git fetch origin
        git reset --hard origin/master
        
        # Install dependencies
        composer install --no-interaction --prefer-dist --no-progress --optimize-autoloader
        
        # Clear cache
        php bin/console cache:clear
        php bin/console cache:warmup
        
        # Run migrations
        php bin/console doctrine:migrations:migrate --no-interaction
        
        # Restart nginx
        sudo systemctl restart nginx
        
          # Ensure proper permissions
        sudo chown -R www-data:www-data /var/www/recruitment-backend
        sudo chmod -R 755 /var/www/recruitment-backend
        
        # Ensure proper permissions for uploads
        mkdir -p /var/www/recruitment-backend/public/uploads/resumes
        sudo chown -R www-data:www-data /var/www/recruitment-backend/public/uploads/resumes
        sudo chmod -R 770 /var/www/recruitment-backend/public/uploads/resumes
        
        # Ensure cache and logs are writable
        sudo chown -R www-data:www-data /var/www/recruitment-backend/var/cache /var/www/recruitment-backend/var/log
        sudo chmod -R 775 /var/www/recruitment-backend/var/cache /var/www/recruitment-backend/var/log
        EOF
