name: Deploy to Azure VPS

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install SSH key
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add known hosts
        run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Run deployment commands
        run: |
          ssh ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} << 'EOF'
          
          sudo chown -R www-data:www-data /var/www/recruitment-backend
          sudo find /var/www/recruitment-backend -type d -exec chmod 755 {} \;
          sudo find /var/www/recruitment-backend -type f -exec chmod 644 {} \;
          
          cd /var/www/recruitment-backend
          
          git config --global --add safe.directory /var/www/recruitment-backend
          git fetch origin
          git reset --hard origin/master
          
          composer install --no-interaction --prefer-dist --no-progress --optimize-autoloader
          
          mkdir -p var/cache var/log public/uploads/resumes
          find var/cache var/log -type d -exec chmod 775 {} \;
          find var/cache var/log -type f -exec chmod 664 {} \;
          chmod -R 775 public/uploads
          
          sudo -u www-data php bin/console cache:clear
          sudo -u www-data php bin/console cache:warmup
          sudo -u www-data php bin/console doctrine:migrations:migrate --no-interaction
          
          sudo chown -R www-data:www-data var/cache/dev/doctrine/orm/Proxies
          sudo chmod -R 775 var/cache/dev/doctrine/orm/Proxies
          
          sudo systemctl restart nginx
          EOF
