name: Deploy to Azure VPS

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install SSH key
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add known hosts
        run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Run deployment commands
        run: |
          ssh ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} << 'EOF'

          cd /var/www/recruitment-backend

          git config --global --add safe.directory /var/www/recruitment-backend
          git fetch origin
          git reset --hard origin/master

          composer install --no-interaction --prefer-dist --no-progress --optimize-autoloader

          mkdir -p var var/cache var/log public/uploads/resumes

          find . -type f -exec chmod 644 {} \;
          find . -type d -exec chmod 755 {} \;

          chmod 755 bin/console

          HTTPDUSER="www-data"

          setfacl -dR -m u:"$HTTPDUSER":rwX -m u:$(whoami):rwX var
          setfacl -R -m u:"$HTTPDUSER":rwX -m u:$(whoami):rwX var

          setfacl -dR -m u:"$HTTPDUSER":rwX -m u:$(whoami):rwX public/uploads/resumes
          setfacl -R -m u:"$HTTPDUSER":rwX -m u:$(whoami):rwX public/uploads/resumes

          php bin/console cache:warmup --env=prod

          sudo systemctl restart nginx
          EOF