name: CI/CD for Symfony

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  ci:
    name: Run Symfony Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          tools: composer, symfony
          coverage: none

      - name: Install Dependencies
        run: composer install --no-interaction --prefer-dist --no-progress

      - name: Run Symfony Linter
        run: php bin/console lint:yaml config --env=prod

      - name: Run PHPUnit Tests
        run: ./vendor/bin/phpunit --testdox

  cd:
    name: Deploy to Azure VPS
    runs-on: ubuntu-latest
    needs: ci
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Deploy to Azure VPS
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd /var/www/recruitment-backend
            git pull origin master
            composer install --no-interaction --prefer-dist --no-progress
            php bin/console cache:clear
            php bin/console cache:warmup
            php bin/console doctrine:migrations:migrate --no-interaction
            systemctl restart nginx
